{{- if .Values.podSecurityPolicies.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "argocd-ecr-updater.fullname" . }}
  labels:
    chart: {{ template "argocd-ecr-updater.chart" . }}
    app: {{ template "argocd-ecr-updater.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "argocd-ecr-updater.fullname" . }}
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceAccount.create  }}
  name: {{ template "argocd-ecr-updater.fullname" . }}
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "argocd-ecr-updater.fullname" . }}
  labels:
    chart: {{ template "argocd-ecr-updater.chart" . }}
    app: {{ template "argocd-ecr-updater.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "argocd-ecr-updater.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "argocd-ecr-updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
